# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [20]:
dataset = pd.read_csv('Dataset train.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [22]:
print(X_train)

[[5.310e+02 0.000e+00 1.100e+00 ... 0.000e+00 1.000e+00 0.000e+00]
 [7.640e+02 1.000e+00 1.200e+00 ... 1.000e+00 1.000e+00 0.000e+00]
 [1.812e+03 1.000e+00 1.300e+00 ... 1.000e+00 1.000e+00 1.000e+00]
 ...
 [1.190e+03 0.000e+00 2.000e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [1.191e+03 0.000e+00 2.400e+00 ... 1.000e+00 1.000e+00 1.000e+00]
 [7.060e+02 0.000e+00 5.000e-01 ... 1.000e+00 0.000e+00 1.000e+00]]


In [23]:
print(y_train)

[2 2 3 ... 3 0 1]


In [24]:
print(X_test)

[[1.454e+03 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [1.092e+03 1.000e+00 5.000e-01 ... 0.000e+00 1.000e+00 0.000e+00]
 [1.524e+03 1.000e+00 1.800e+00 ... 1.000e+00 0.000e+00 1.000e+00]
 ...
 [1.759e+03 1.000e+00 1.400e+00 ... 1.000e+00 1.000e+00 0.000e+00]
 [5.140e+02 1.000e+00 1.600e+00 ... 1.000e+00 1.000e+00 1.000e+00]
 [1.410e+03 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]]


In [25]:
print(y_test)

[3 0 2 2 2 0 0 3 3 1 1 3 0 2 3 0 3 2 2 1 0 0 3 1 2 2 3 1 3 1 1 0 2 0 1 3 0
 0 3 3 3 1 3 3 1 3 0 1 3 1 1 3 0 3 0 3 2 2 0 3 3 1 3 2 1 2 3 2 2 2 3 2 1 0
 1 3 2 2 1 2 3 3 3 0 0 0 2 1 2 3 1 2 2 1 0 3 3 3 0 3 1 1 2 1 3 2 2 3 2 3 3
 0 0 1 3 3 0 0 1 0 0 3 2 2 1 1 1 1 0 2 1 3 2 3 3 3 3 2 0 1 1 2 1 3 1 3 0 0
 2 0 1 1 1 1 3 0 0 3 1 3 2 1 3 1 2 3 3 2 1 0 3 1 2 3 3 0 2 2 3 0 2 1 0 1 2
 1 2 0 3 3 1 1 0 2 3 0 1 2 2 0 3 3 3 1 2 3 3 3 0 0 0 2 3 3 0 0 1 3 1 3 3 3
 0 0 2 3 3 1 0 2 0 0 0 3 2 0 2 2 1 1 0 2 3 3 0 0 1 3 3 2 3 0 3 1 1 0 2 3 3
 2 0 0 1 2 3 2 2 3 2 1 0 3 3 2 1 3 2 2 2 1 0 2 2 1 0 0 2 2 2 2 0 1 3 0 1 2
 3 0 2 0 1 1 3 0 0 2 3 1 2 0 2 0 3 0 3 3 2 3 1 2 2 1 1 1 0 1 0 3 1 0 3 0 0
 1 3 0 3 1 2 0 1 3 0 2 2 1 2 1 1 0 2 0 0 3 1 2 3 2 2 0 3 2 2 1 3 2 3 3 3 0
 2 0 3 0 1 1 2 2 1 3 1 2 0 1 2 3 0 0 1 3 0 3 0 2 2 1 1 0 2 1 0 1 3 0 3 3 0
 2 1 3 1 1 3 2 0 3 2 2 0 0 3 0 1 1 1 3 2 3 2 0 3 0 0 1 3 0 0 3 2 2 2 3 0 0
 1 2 1 2 0 3 3 0 3 3 0 2 2 1 0 2 2 1 3 2 2 0 2 0 3 3 2 1 0 3 1 2 0 0 1 3 0
 3 0 0 2 2 0 1 3 0 3 2 1 

## Feature Scaling

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [27]:
print(X_train)

[[-1.58954736 -0.97628121 -0.54409463 ... -1.77951304  1.01072417
  -1.02840321]
 [-1.06204271  1.02429504 -0.42202734 ...  0.56195149  1.01072417
  -1.02840321]
 [ 1.31059626  1.02429504 -0.29996004 ...  0.56195149  1.01072417
   0.97238125]
 ...
 [-0.09759213 -0.97628121  0.55451104 ... -1.77951304 -0.98938962
   0.97238125]
 [-0.09532817 -0.97628121  1.04278023 ...  0.56195149  1.01072417
   0.97238125]
 [-1.19335288 -0.97628121 -1.27649842 ...  0.56195149 -0.98938962
   0.97238125]]


In [28]:
print(X_test)

[[ 0.50009554  1.02429504 -1.27649842 ...  0.56195149  1.01072417
  -1.02840321]
 [-0.31946105  1.02429504 -1.27649842 ... -1.77951304  1.01072417
  -1.02840321]
 [ 0.65857334  1.02429504  0.31037645 ...  0.56195149 -0.98938962
   0.97238125]
 ...
 [ 1.19060593  1.02429504 -0.17789274 ...  0.56195149  1.01072417
  -1.02840321]
 [-1.62803483  1.02429504  0.06624185 ...  0.56195149  1.01072417
   0.97238125]
 [ 0.40048093  1.02429504 -1.27649842 ...  0.56195149  1.01072417
  -1.02840321]]


## Training the K-NN model on the Training set

In [29]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

## Predicting a new result

In [30]:
print(classifier.predict(sc.transform([[30,87000]])))

ValueError: ignored

## Predicting the Test set results

In [31]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 3]
 [0 0]
 [2 2]
 [0 2]
 [1 2]
 [0 0]
 [0 0]
 [2 3]
 [3 3]
 [2 1]
 [1 1]
 [3 3]
 [1 0]
 [2 2]
 [2 3]
 [0 0]
 [3 3]
 [2 2]
 [2 2]
 [0 1]
 [1 0]
 [0 0]
 [3 3]
 [0 1]
 [2 2]
 [2 2]
 [3 3]
 [0 1]
 [3 3]
 [0 1]
 [0 1]
 [3 0]
 [1 2]
 [1 0]
 [1 1]
 [3 3]
 [0 0]
 [0 0]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [1 3]
 [2 1]
 [3 3]
 [0 0]
 [2 1]
 [2 3]
 [0 1]
 [0 1]
 [2 3]
 [0 0]
 [2 3]
 [0 0]
 [2 3]
 [2 2]
 [2 2]
 [0 0]
 [3 3]
 [2 3]
 [3 1]
 [1 3]
 [3 2]
 [0 1]
 [1 2]
 [2 3]
 [2 2]
 [1 2]
 [3 2]
 [2 3]
 [3 2]
 [1 1]
 [0 0]
 [1 1]
 [3 3]
 [3 2]
 [2 2]
 [1 1]
 [0 2]
 [3 3]
 [3 3]
 [2 3]
 [1 0]
 [0 0]
 [1 0]
 [1 2]
 [1 1]
 [1 2]
 [1 3]
 [1 1]
 [1 2]
 [1 2]
 [0 1]
 [1 0]
 [3 3]
 [3 3]
 [2 3]
 [0 0]
 [3 3]
 [0 1]
 [1 1]
 [1 2]
 [1 1]
 [1 3]
 [2 2]
 [0 2]
 [2 3]
 [2 2]
 [2 3]
 [2 3]
 [1 0]
 [2 0]
 [2 1]
 [1 3]
 [2 3]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 3]
 [1 2]
 [3 2]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [3 2]
 [0 1]
 [3 3]
 [2 2]
 [3 3]
 [2 3]
 [3 3]
 [2 3]
 [2 2]
 [1 0]
 [0 1]
 [2 1]
 [2 2]
 [0 1]

## Making the Confusion Matrix

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[84 36  3  1]
 [37 50 19  4]
 [14 46 49 16]
 [ 0 13 62 66]]


0.498

## Visualising the Training set results

In [33]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 1),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 1))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('K-NN (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

ValueError: ignored

## Visualising the Test set results

In [34]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 1),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 1))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('K-NN (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

ValueError: ignored