# Multiple Linear Regression

## Importing the libraries

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [13]:
dataset = pd.read_csv('Dataset train.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [14]:
print(X)

[[8.42e+02 0.00e+00 2.20e+00 ... 0.00e+00 0.00e+00 1.00e+00]
 [1.02e+03 1.00e+00 5.00e-01 ... 1.00e+00 1.00e+00 0.00e+00]
 [5.63e+02 1.00e+00 5.00e-01 ... 1.00e+00 1.00e+00 0.00e+00]
 ...
 [1.91e+03 0.00e+00 9.00e-01 ... 1.00e+00 1.00e+00 0.00e+00]
 [1.51e+03 0.00e+00 9.00e-01 ... 1.00e+00 1.00e+00 1.00e+00]
 [5.10e+02 1.00e+00 2.00e+00 ... 1.00e+00 1.00e+00 1.00e+00]]


## Splitting the dataset into the Training set and Test set

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [16]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [17]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 2.72  3.  ]
 [-0.19  0.  ]
 [ 1.8   2.  ]
 [ 1.53  2.  ]
 [ 2.38  2.  ]
 [-0.34  0.  ]
 [-0.15  0.  ]
 [ 2.5   3.  ]
 [ 2.78  3.  ]
 [ 1.14  1.  ]
 [ 0.62  1.  ]
 [ 2.75  3.  ]
 [ 0.33  0.  ]
 [ 1.8   2.  ]
 [ 2.94  3.  ]
 [ 0.23  0.  ]
 [ 3.42  3.  ]
 [ 1.75  2.  ]
 [ 1.8   2.  ]
 [ 0.85  1.  ]
 [ 0.27  0.  ]
 [ 0.25  0.  ]
 [ 3.3   3.  ]
 [ 0.97  1.  ]
 [ 1.58  2.  ]
 [ 1.7   2.  ]
 [ 3.75  3.  ]
 [ 1.12  1.  ]
 [ 3.35  3.  ]
 [ 1.18  1.  ]
 [ 1.36  1.  ]
 [ 0.3   0.  ]
 [ 1.61  2.  ]
 [ 0.5   0.  ]
 [ 1.54  1.  ]
 [ 3.36  3.  ]
 [-0.58  0.  ]
 [-0.08  0.  ]
 [ 3.08  3.  ]
 [ 3.23  3.  ]
 [ 2.38  3.  ]
 [ 1.33  1.  ]
 [ 2.95  3.  ]
 [ 2.52  3.  ]
 [ 1.19  1.  ]
 [ 3.46  3.  ]
 [-0.31  0.  ]
 [ 1.21  1.  ]
 [ 2.51  3.  ]
 [ 1.18  1.  ]
 [ 0.97  1.  ]
 [ 2.63  3.  ]
 [ 0.26  0.  ]
 [ 2.57  3.  ]
 [-0.57  0.  ]
 [ 2.36  3.  ]
 [ 2.31  2.  ]
 [ 1.54  2.  ]
 [-0.21  0.  ]
 [ 2.59  3.  ]
 [ 2.65  3.  ]
 [ 1.23  1.  ]
 [ 2.45  3.  ]
 [ 1.65  2.  ]
 [ 1.22  1.  ]
 [ 2.29  2.  ]
 [ 2.75  3